name: 'dbt_tutorial'
version: '1.0.0'
config-version: 2

profile: 'dbt_demo'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_tutorial:
    staging:
      +materialized: view       # staging models → views in warehouse schema
    transformation:
      +materialized: view      # transformation models → views in warehouse schema
    serving:
      +materialized: table